'use strict';

var assert = require('yeoman-assert');
var fs = require('fs');
var os = require('os');
var path = require('path');
var test = require('yeoman-test');
var yaml = require('js-yaml');
var _ = require('lodash');

var files = require('./environment.files');
var schema = require('./schema-assert');

var describeYaml = function() {
  var items = files.yaml;

  return function() {
    Object.keys(items).forEach(function(filepath) {
      it('should have a valid "' + items[filepath] + '"', function() {
        schema.assertYaml(filepath);
      });
    });
  };
};

var describeJson = function(appDir) {
  var items = files.json;

  return function() {
    Object.keys(items).forEach(function(filepath) {
      it('should have a valid "' + items[filepath] + '"', function() {
        schema.assertJson(appDir, filepath);
      });
    });
  };
};


describe('p2:environment', function() {
  var appDir = path.join(os.tmpdir(), './temp-test-environment');
  console.log('Environment tests will be generated in "' + appDir + '"');

  describe('minimal configuration', function() {
    before(function(done) {
      test.run(path.join(__dirname, '../environment'))
        .inDir(appDir)
        .withPrompts({
          cacheInternal: 'database',
          drupalDistroVersion: '8.x',
          // This could be excluded, but would get the temp base directory.
          domain: 'drupal8',
          environments: [],
          projectName: 'drupal8',
          proxyCache: 'none',
          webserver: 'apache'
        })
        .withOptions({
          'skip-install': true,
          force: true
        })
        .on('end', done);
    });

    it('should have a minimal set of files', function() {
      assert.file(files.minimum);
      assert.file(files.minimumJenkins);
    });

    it('should not include the extended files added with more opt-ins', function() {
      assert.noFile(files.extended);
      assert.noFile(files.extendedJenkins);
    });

    describe('provides have valid JSON files', describeJson(appDir));

    describe('Docker', function() {
      describe('has YAML configuration', describeYaml());
      describe('Operational Services - Local', function() {
        var manifest;

        before(function() {
          manifest = yaml.safeLoad(fs.readFileSync('docker-compose.yml', 'utf8'));
        });

        it('should include a database', function() {
          assert.ok(manifest['services']['db'] && manifest['services']['db']['image']);
        });
        it('should include an application server', function() {
          assert.ok(manifest['services']['www'] && manifest['services']['www']['image']);
        });
        it('should use apache-php:php70 with Drupal 8', function() {
          assert.ok(manifest['services']['www']['image'] == 'phase2/apache-php:php70');
        });
        it('should not have a cache service', function() {
          assert.ok(!manifest['services']['cache']);
        });
        it('should not have a proxy service', function() {
          assert.ok(!manifest['services']['proxy']);
        });
        it('should not have a mail service', function() {
          assert.ok(!manifest['services']['mail']);
        });
      });
    });
  });

  describe('extended configuration', function() {
    before(function(done) {
      test.run(path.join(__dirname, '../environment'))
        .inDir(appDir)
        .withPrompts({
          cacheInternal: 'memcache',
          drupalDistroVersion: '8.x',
          // This could be excluded, but would get the temp base directory.
          domain: 'drupal8',
          environments: [ 'dev', 'qa', 'review' ],
          mailhog: true,
          projectName: 'drupal8',
          proxyCache: 'varnish',
          webserver: 'apache'
        })
        .withOptions({
          'skip-install': true,
          force: true
        })
        .on('end', done);
    });

    it('should include the minimal set of files', function() {
      assert.file(files.minimum);
      // This check ensures Jenkins files are generated by the sub-generator.
      assert.file(files.minimumJenkins);
    });

    it('should have additional files beyond minimal', function() {
      assert.file(files.extended);
      // This check ensures Jenkins files are generated by the sub-generator.
      assert.file(files.extendedJenkins);
    });

    describe('provides valid JSON files', describeJson(appDir));

    describe('Docker', function() {
      describe('has YAML configuration', describeYaml());
      describe('CLI Services - Local', function() {
        var manifest;

        before(function() {
          manifest = yaml.safeLoad(fs.readFileSync('build.yml', 'utf8'));
        });

        it('should use the PHP7 build container with Drupal 8', function() {
          assert.ok(manifest['services']['base']['image'] == 'phase2/devtools-build:php70');
        });

      });
      describe('Operational Services - Local', function() {
        var manifest;

        before(function() {
          manifest = yaml.safeLoad(fs.readFileSync('docker-compose.yml', 'utf8'));
        });

        describe('Core Services', function() {
          it('should include a database', function() {
            assert.ok(manifest['services']['db'] && manifest['services']['db']['image']);
          });
          it('should include an application server', function() {
            assert.ok(manifest['services']['www'] && manifest['services']['www']['image']);
          });
          it('should include an internal caching service', function() {
            assert.ok(manifest['services']['cache'] && manifest['services']['cache']['image']);
          });
          it('should include a reverse-proxy cache', function() {
            assert.ok(manifest['services']['proxy'] && manifest['services']['proxy']['image']);
          });
          it('should include a mail-handling services', function() {
            assert.ok(manifest['services']['mail'] && manifest['services']['mail']['image']);
          });
        });
        describe('Docker Images', function() {
          it('should use apache-php with Drupal 8', function() {
            assert.ok(manifest['services']['www']['image'] == 'phase2/apache-php:php70');
          });
          it('should use memcache for internal caching', function() {
            assert.ok(manifest['services']['cache'] && manifest['services']['cache']['image'] == 'phase2/memcache');
          });
          it('should use Varnish for reverse-proxy caching', function() {
            assert.ok(manifest['services']['proxy'] && manifest['services']['proxy']['image'] == 'phase2/varnish:4.0');
          });
        });
      });

      describe('Operational Services - Dev Cloud', function() {
        var manifest;

        before(function() {
          manifest = yaml.safeLoad(fs.readFileSync('docker-compose.devcloud.yml', 'utf8'));
        });

        describe('Core Services', function() {
          it('should include a database', function() {
            assert.ok(manifest['services']['db']);
          });
          it('should include an application server', function() {
            assert.ok(manifest['services']['www']);
          });
          it('should include an intenral caching service', function() {
            assert.ok(manifest['services']['cache']);
          });
          it('should include a reverse-proxy cache', function() {
            assert.ok(manifest['services']['proxy']);
          });
          it('should include a mail-handling services', function() {
            assert.ok(manifest['services']['mail']);
          });
        });

        describe('Docker Images', function() {
          it('should extend from docker-compose.yml for cache container', function() {
            assert.ok(manifest['services']['cache']['extends']['file'] === 'docker-compose.yml');
          });
          it('should extend from docker-compose.yml for db container', function() {
            assert.ok(manifest['services']['db']['extends']['file'] === 'docker-compose.yml');
          });
          it('should use apache-php:php70 with Drupal 8', function() {
            assert.ok(manifest['services']['www']['image'] == 'phase2/apache-php:php70');
          });
          it('should use Varnish for reverse-proxy caching', function() {
            assert.ok(manifest['services']['proxy']['image'] == 'phase2/varnish:4.0');
          });
        });
      });
    });
  });
});
